### ISSUE TITLE
FYI:  This script is out of date

### ISSUE THREAD

**Issue by hjmjohnson** [jason-fries/drugsatfda-db#1]
Newly downloaded databases have different names and structures.

**Comment by hjmjohnson** [comment]
See git@github.com:adintegra/drugsatfda-db.git for updated version.

**Comment by jason-fries** [comment]
Thanks @hjmjohnson If you wanted to submit a PR with the updated code I'm happy to merge. Otherwise this repo isn't actively being maintained.
